version: '3'
services:

    script:
        # build . aponta para a pasta onde contem o dockerfile a ser construida
        build: .
        volumes:
        # esquerda = host
            - ./:/home/script
        command: python3 script_popula_neo4j.py                
    neo4j:
        image: neo4j:latest
        ports:
            - '7474:7474'
            - '7687:7687'
        volumes:
            - $HOME/neo4j/conf:/conf           
            - $HOME/neo4j/neo4j-core1/data:/data
            - $HOME/neo4j/import:/import

        environment:
            NEO4J_AUTH: neo4j/45l69k
            #NEO4J_dbms_security_procedures_unrestricted: apoc.*,algo.*                
            #NEO4J_dbms_connectors_default__listen__address: 0.0.0.0



